FROM node:22-alpine

# RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

WORKDIR /app

COPY . .
RUN npm install -g npm@10.9.3

RUN npm i

RUN npx turbo run build --filter=cms

WORKDIR /app/apps/cms

EXPOSE 1337

CMD ["npm", "run", "start"]