FROM node:22-alpine

WORKDIR /app

COPY . .
RUN npm install -g npm@10.9.3

RUN rm -f package-lock.json

RUN npm i
    
RUN npx turbo run build --filter=web

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["npm", "run", "start"]